### ISSUE TITLE
Lab Report 3 Feedback

### ISSUE THREAD

**Issue by farnaf** [tylermeyers/CSE15l-lab-reports#3]
Here is your feedback for Lab Report 3 - Copy whole directories with `scp -r`:

- [x] Show copying your whole markdown-parse directory to your `ieng6` account
- [x] Show logging into your `ieng6` account after doing this and compiling and running the tests for your repository
  - show the login in the screenshot as well
- [ ] Show (like in the last step of the first lab) combining `scp`, `;`, and `ssh` to copy the whole directory and run the tests in one line.
  - show the terminal output for this one as well, once resolved(:

Additional comments from your grader:
nice job 😃
feel free to comment below any questions related to the rubric/feedback!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by farnaf** [comment]
Hi there, I am looking at your new screenshot.. are you running the tests in https://github.com/tylermeyers/markdown-parse?

What is the command you're using to copy and run the tests remotely?

**Comment by tylermeyers** [comment]
Yea I believe so, I updated the markdown-parse in my files to match the markdown-parse in my github repo just in case and ran it again but for whatever reason a bunch of them fail even though previously like 2 only failed.

**Comment by tylermeyers** [comment]
scp -r *.java *.md lib/ cs15lwi22abe@ieng6.ucsd.edu:markdown-parse;ssh cs15lwi22abe@ieng6.ucsd.edu "cd markdown-parse; /software/CSE/oracle-java-se-14/jdk-14.0.2/bin/javac MarkdownParse.java; /software/CSE/oracle-java-se-14/jdk-14.0.2/bin/javac -classpath .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar MarkdownParseTest.java; /software/CSE/oracle-java-se-14/jdk-14.0.2/bin/java -classpath .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar org.junit.runner.JUnitCore MarkdownParseTest"

I tried compiling markdownparse.java and for whatever reason, it indicated that I had failed 16/22 tests which are more tests than it had said in my original screenshot so it's being a bit weird lol. Thank you for trying to help though!

**Comment by tylermeyers** [comment]
Oh i also realized that I forgot to put "javac" aswell

**Comment by farnaf** [comment]
That's good, because I ran your tests and there are 22 tests

I mentioned this on Gradescope too, seems like the reason you're failing 7 extra tests is because it cannot find the files that are in joe-test-files. Does this command copy *everything* : scp -r *.java *.md lib/ [cs15lwi22abe@ieng6.ucsd.edu](mailto:cs15lwi22abe@ieng6.ucsd.edu) ?

**Comment by tylermeyers** [comment]
I've tried using the other way but I still get the error scp -r . cs15lwi22abe@ieng6.ucsd.edu:~/markdown-parse;ssh cs15lwi22abe@ieng6.ucsd.edu "cd markdown-parse; /software/CSE/oracle-java-se-14/jdk-14.0.2/bin/javac MarkdownParse.java; /software/CSE/oracle-java-se-14/jdk-14.0.2/bin/javac -classpath .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar MarkdownParseTest.java; /software/CSE/oracle-java-se-14/jdk-14.0.2/bin/java -classpath .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar org.junit.runner.JUnitCore MarkdownParseTest"

**Comment by farnaf** [comment]
Is it the same exact error as before?

**Comment by tylermeyers** [comment]
oh it said I failed 9/22 this time

**Comment by farnaf** [comment]
Yeah that's the output we expect! (the failed tests now are related to bugs with MarkdownParse.java not issues with MarkdownParseTest.java)

Nice work, I'll update your Gradescope score

**Comment by tylermeyers** [comment]
Ohhhhhhhhhhh I thought I was still running into the error. Thank you! I appreciate it a lot, but I should probably go into tutor hours next time lol
